apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-gate
  namespace: argocd
spec:
  destination:
    namespace: admin-gate
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/tenshi-lab-kube/Admin-Gate.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
